General:
  Measurement: "minimal_example"
  POI: "Signal_norm"
  HistogramFolder: "histograms/"
  InputPath: "ntuples/{SamplePaths}"

Regions:
  - Name: "Signal_region"
    Variable: "jet_pt"
    Filter: "lep_charge > 0"
    Binning: [200, 300, 400, 500, 600]

Samples:
  - Name: "Data"
    Tree: "pseudodata"
    SamplePaths: "data.root"
    Data: True

  - Name: "Signal"
    Tree: "signal"
    SamplePaths: "prediction.root"
    Weight: "weight"

  - Name: "Background"
    Tree: "background"
    SamplePaths: "prediction.root"
    Weight: "weight"

Systematics:
  - Name: "Luminosity"
    Up:
      Normalization: 0.05
    Down:
      Normalization: -0.05
    Samples: ["Signal", "Background"]
    Type: "Normalization"

  - Name: "Modeling"
    Up:
      SamplePaths: "prediction.root"
      Tree: "background_varied"
    Down:
      Symmetrize: True
    Samples: "Background"
    Type: "NormPlusShape"

  - Name: "WeightBasedModeling"
    Up:
      Weight: "weight_up"
    Down:
      Weight: "0.7*weight"
    Samples: "Background"
    Type: "NormPlusShape"

NormFactors:
  - Name: "Signal_norm"
    Samples: "Signal"
    Nominal: 1
    Bounds: [0, 10]
