General:
  Measurement: "My fit"
  POI: "Signal strength"

Samples:
  - Name: "Data"
    Tree: "pseudodata"
    Path: "ntuples/data.root"
    Color: "#000000"
    Data: True

  - Name: "Background"
    Tree: "background"
    Path: "ntuples/prediction.root"
    Weight: "weight"
    Color: "#F55EE33"

  - Name: "Signal"
    Tree: "signal"
    Path: "ntuples/prediction.root"
    Weight: "weight"
    Color: "#FFAA55"

Regions:
  - Name: "Signal Region"
    Variable: "jet_pt"
    Binning: [0, 100, 200, 300, 400, 500, 600, 700, 800, 900, 1000]

Systematics:
  - Name: "Luminosity"
    OverallDown: -0.02
    OverallUp: 0.02
    Samples: ALL
    Type: OVERALL

NormFactors:
  - Name: "Signal strength"
    Nominal: 1
    Min: 0
    Max: 5
    Samples: "Signal"
